name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  package-haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: feathersui-minimal-theme-haxelib
          path: |
            assets/
            src/
            haxelib.json
            include.xml
            README.md
            LICENSE
            NOTICE
            CHANGELOG.md
          if-no-files-found: error

  build-flash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install feathersui --quiet
          haxelib dev feathersui-minimal-theme ${{ github.workspace }}
      - name: Build Flash .swc library
        run: haxelib run openfl build flash -debug
      - uses: actions/upload-artifact@v3
        with:
          name: feathersui-minimal-theme-swc
          path: bin/flash/bin/feathersui-minimal-theme.swc
          if-no-files-found: error
